# Generated by Django 6.0 on 2026-01-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profiles/default_avatar.png', null=True, upload_to='profiles/'),
        ),
    ]
