# Generated by Django 6.0 on 2026-01-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_section_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
