# Generated by Django 6.0 on 2026-01-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_lesson_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, default='course_thumbnails/default-course-thumbnail.png', null=True, upload_to='course_thumbnails/'),
        ),
    ]
